---
title: "caminaconmigo"
subtitle: "cccc | Molecular Geneticist"
# `profile.jpg` photo by Jan Tinneberg on https://unsplash.com
website:
  favicon: caminaconmigo_logo.png
---


## Education

Universidade Federal de Viçosa, Brasil \| Viçosa \| 2024 - 2025

Universidad Nacional Agraria La Molina, Perú \| Lima \| 2015 - 2020

## Experience

International Potato Center \| Job title \| April 20XX - present


:::{.section-alt}
:::{.column-screen}
:::{.column-body}

# Welcome to ALA Labs

This site is a resource for coding projects that use data sourced from  
[the ALA](https://ala.org.au/).

We hope that users will find interesting content, whether their focus is
ecological modelling, data visualisation, or simply investigating the
natural world through a digital lens.

Enjoy!

:::
:::
:::

:::{.section-alt-t}
:::{.column-screen}
:::{.column-body}

# Welcome to ALA Labs

This site is a resource for coding projects that use data sourced from  
[the ALA](https://ala.org.au/).

We hope that users will find interesting content, whether their focus is
ecological modelling, data visualisation, or simply investigating the
natural world through a digital lens.

Enjoy!

:::
:::
:::
